# Introduction to Python

You will be using Python as the main programming language in this course. This Lab provides you with a quick guide for programming in Python (from w3schools). You can learn more about Python through the complete [Python Tutorial](https://docs.python.org/3/tutorial/) or by signing up for free online courses on Python.

You will also learn how to use the `NumPy` library in Python as it is an essential tool for Data Science and Machine Learning.

## Python Indentations

The indentation in Python is very important as it indicates a block of code. See the example below.

```Python
if 5 > 2:
  print("Five is greater than two!")
```

The equivalent of the above code is C++ is below.

```C++
if 5 > 2
{
  cout<<"Five is greater than two!";
}
```

If you skip the indentation in the above Python example you will see the following error.

In [2]:
if 5 > 2:
print("Five is greater than two!")

IndentationError: expected an indented block (<ipython-input-2-a314491c53bb>, line 2)

## Comments

You can use the `#` operator to start a comment. Just like the `//` in C++. See the example below.

```Python
#This is a comment.
print("Hello, World!")
```

## Variables

Unlike other programming languages, you do not have to declare a variable in Python. A variable is created the moment you first assign a value to it. See the example below.

```Python
a = 5      # a is a variable of type integer
b = 1.2    # b is a variable of type float
c = "Asad" # c is a variable of type string
```

The following rules apply for naming variables in Python:

* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
* Variable names are case-sensitive (age, Age and AGE are three different variables)

## Casting

Casting in python is done using constructor functions:

* int() - constructs an integer number from an integer literal, a float literal (by rounding down to the previous whole number), or a string literal (providing the string represents a whole number)
* float() - constructs a float number from an integer literal, a float literal or a string literal (providing the string represents a float or an integer)
* str() - constructs a string from a wide variety of data types, including strings, integer literals and float literals

See the example below.

```Python
x = int(1)       # x will be 1
y = int(2.8)     # y will be 2
z = int("3")     # z will be 3
w = float("4.2") # w will be 4.2
s = str(3.0)     # s will be '3.0'
```

## Collections (Arrays)

There are four collection data types in the Python programming language:

* **List** is a collection which is ordered and changeable. Allows duplicate members.
* **Tuple** is a collection which is ordered and unchangeable. Allows duplicate members.
* **Set** is a collection which is unordered and unindexed. No duplicate members.
* **Dictionary** is a collection which is unordered, changeable and indexed. No duplicate members.

### List

A list is a collection which is ordered and changeable. In Python lists are written with square brackets. See the example below.

```Python
my_list = ["apple", "banana", "cherry"]
```

You access the list items by referring to the index number. See the example below.

```Python
print(my_list[1])
```

The output would be `banana`

You can loop through the list items by using a `for` loop. See the example below.

```Python
for x in my_list:
  print(x)
```

The output would be
> apple

> banana

> cherry

### Tuple

A tuple is a collection which is ordered and **unchangeable**. In Python tuples are written with round brackets. See the example below.

```Python
my_tuple = ("apple", "banana", "cherry")
```

### Set

A set is a collection which is unordered and unindexed. In Python sets are written with curly brackets. See the example below.

```Python
my_set = {"apple", "banana", "cherry"}
```

### Dictionary

A dictionary is a collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets, and they have keys and values. See the example below.

```Python
my_dict = {"brand": "Ford", "model": "Mustang", "year": 1964}
```

You can access the items of a dictionary by referring to its key name, inside square brackets. See the example below.

```Python
x = my_dict["model"]
```

## Conditions and _if_ statements

An _if statement_ is written by using the if keyword. See the example below.

```Python
a = 100
b = 200
if b > a:
  print("b is greater than a")
```

The `elif` keyword is Python's way of saying "if the previous conditions were not true, then try this condition".

```Python
a = 1
b = 1
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
```

The `else` keyword catches anything which is not caught by the preceding conditions.

```Python
a = 200
b = 100
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")
```

The `and` keyword is a logical operator, and is used to combine conditional statements. See the example below.

```Python
if a > b and c > a:
  print("Both conditions are True")
```

The `or` keyword is a logical operator, and is used to combine conditional statements. See the example below.

```Python
if a > b or a > c:
  print("At least one of the conditions is True")
```

## Loops

Python has two primitive loop commands:
* **while** loops
* **for** loops

### The _while_ Loop

With the `while` loop we can execute a set of statements as long as a condition is true. See the example below.

```Python
i = 0
while i < 10:
  print(i)
  i += 1
```

### The _break_ Statement

With the `break` statement we can stop the loop even if the while condition is true. See the example below.

```Python
i = 0
while i < 10:
  print(i)
  if i == 3:
    break
  i += 1
```

### The _continue_ Statement

With the `continue` statement we can stop the current iteration, and continue with the next. See the example below.

```Python
i = 0
while i < 10:
  i += 1 
  if i == 3:
    continue
  print(i)
```

### The _for_ Loop

A `for` loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string). With the `for` loop we can execute a set of statements, once for each item in a list, tuple, set etc.

You can use `break` and `continue` statements in `for` loops.

```Python
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
```

#### The _range()_ Function

To loop through a set of code a specified number of times, we can use the `range()` function. It returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number. See the example below.

```Python
# values from 0 to 5
for x in range(6):
  print(x)
```

It is possible to change the `range()` default values. The example below iterates from 2 to 29 and increments by 3.

```Python
for x in range(2, 30, 3):
  print(x)
```

## Functions

A **function** is a block of code which only runs when it is called. You can pass data, known as parameters, into a **function**. A **function** can return data as a result.

In Python a **function** is defined using the `def` keyword. See the example below.

```Python
def my_function():
  print("My function!")
```

To call a function, use the function name followed by parenthesis.

```Python
def my_function():
  print("My function!")

my_function()
```

Information can be passed to functions as parameter. Parameters are specified after the function name, inside the parentheses. You can add as many parameters as you want, just separate them with a comma. The following example has a function with one parameter (fname). When the function is called, we pass along a first name, which is used inside the function to print the full name.

```Python
def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")
```

To let a function return a value, you can use the `return` statement. See the example below.

```Python
def my_function(x):
  return 5 * x

print(my_function(3))
```

The output would be `15`.

## Python Lambda

A `lambda` function is a small anonymous function. It can take any number of arguments, but can only have one expression. See the examples below.

```Python
x = lambda a : a + 10
print(x(5))
```

The output would be `15` 

```Python
x = lambda a, b, c : a + b + c
print(x(5, 6, 2))
```

The output would be `13`

The power of `lambda` is better shown when you use them as an anonymous function inside another function. Say you have a function definition that takes one argument, and that argument will be multiplied with an unknown number.

```Python
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))
```

The output would be `22`

## Python Classes/Objects

To create a class, use the keyword `class`.

```Python
class MyClass:
  x = 5
```

Here we will create an object named _obj1_ and print the value of variable _x_.

```Python
p1 = MyClass()
print(p1.x)
```

### The \__init__() Function

The examples above are classes and objects in their simplest form, and are not really useful in real life applications. To understand the meaning of classes we have to understand the built-in `__init__()` function. All classes have a function called `__init__()`, which is always executed when the class is being initiated. Use the `__init__()` function to assign values to object properties, or other operations that are necessary to do when the object is being created. This is similar to a **constructor** in C++.

```Python
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)
```

### The Object Methods

Objects can also contain methods. Methods in objects are functions that belongs to the object.

```Python
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  # "self" is a reference to the current instance of the class, and is used to access the class variables.
  def myfunc(self):
    print("Hello my name is " + self.name)

p1 = Person("John", 36)
p1.myfunc()
```

# NumPy

Python is convenient, but it can also be slow. However, it does allow you to access libraries that execute faster code written in languages like C. NumPy is one such library that provides fast alternatives to math operations in Python and is designed to work efficiently with groups of numbers such as matrices.

NumPy is a large library and we are only going to scratch the surface of it here. If you plan on doing much math with Python, you should definitely spend some time exploring its [documentation](https://docs.scipy.org/doc/numpy/reference/) to learn more.

## Importing NumPy

When importing the `NumPy` library, the convention you will see used most often is to name it **np**.

```Python
import numpy as np 
```

In [3]:
import numpy as np

Now you can use the library by prefixing the names of functions and types with `np.`

## Data Types and Shapes

The most common way to work with numbers in `NumPy` is through `ndarray` objects. They are similar to Python lists, but can have any number of dimensions. Also, `ndarray` supports fast math operations. Since it can store any number of dimensions, you can use `ndarrays` to represent any of the data types we need in Machine Learning such as scalars, vectors, matrices, or tensors.

### Scalars

Scalars in `NumPy` are a bit more involved than in Python. Instead of Python’s basic types like `int`, `float`, etc., `NumPy` lets you specify signed and unsigned types, as well as different sizes. So instead of Python’s `int`, you have access to types like `uint8`, `int8`, `uint16`, `int16`, and so on.

These types are important because every object you make (vectors, matrices, tensors) eventually stores scalars. And when you create a `NumPy` array, you can specify the type - but every item in the array must have the same type. In this regard, `NumPy` arrays are more like `C` arrays than Python lists.

If you want to create a `NumPy` array that holds a scalar, you do so by passing the value to `NumPy`'s array function.

```Python
s = np.array(5)
```

Even though scalars are inside arrays, you still use them like a normal scalar. See the example below.

```Python
x = s + 3
print(x)
```

The output would be `8`.

### Vectors

To create a vector, you would pass a Python list to the array function.

```Python
v = np.array([1,2,3])
```

In [5]:
v = np.array([1,2,3])

If you check a vector's shape attribute, it will return a single number representing the vector's one-dimensional length. In the above example, `v.shape` would return `(3,)`. Now that there is a number, you can see that the shape is a tuple with the sizes of each of the `ndarray`'s dimensions. For scalars it was just an empty tuple, but vectors have one dimension, so the tuple includes a number and a comma. (Python does not understand (3) as a tuple with one item, so it requires the comma. You can access an element within the vector using indices.

```Python
x = v[1]
print(x)
```

The output would be `2`.

In [6]:
x = v[1]
print(x)

2


`NumPy` supports advanced indexing techniques. For example, to access the items from the second element onward, you would write:

```Python
v[1:]
```

In [7]:
print(v[1:])

[2 3]


### Matrices

You create matrices using `NumPy`'s array function. However, instead of just passing in a list, you need to supply a list of lists, where each list represents a row. So to create a 3x3 matrix containing the numbers one through nine, you could do this:

```Python
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
```

In [10]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Checking its shape attribute (`m.shape`) would return the tuple `(3, 3)` to indicate it has two dimensions, each length 3. You can access elements of matrices just like vectors, but using additional index values. So to find the number 6 in the above matrix, you could do this:

```Python
n = m[1][2]
```

In [11]:
n = m[1][2]
print(n)

6


### Tensors

Tensors are just like vectors and matrices, but they can have more dimensions. For example, to create a 3x3x2x1 tensor, you could do the following:

```Python
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
```

In [13]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print(t)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]


`t.shape` would return `(3, 3, 2, 1)`. You can access items just like with matrices, but with more indices. So to find number 16, you could do this:

```Python
n = t[2][1][1][0]
```

In [14]:
n = t[2][1][1][0]
print(n)

16


### Changing Shapes

Sometimes you will need to change the shape of your data without actually changing its contents. For example, you may have a vector, which is one-dimensional, but need a matrix, which is two-dimensional. There are two ways you can do that. Let's say you have the following vector:

`v = np.array([1,2,3,4])`

Calling `v.shape` would return `(4,)`. But what if you want a 1x4 matrix? You can accomplish that with the `reshape` function by writing this:

```Python
x = v.reshape(1,4)
```

In [20]:
v = np.array([1,2,3,4])
print(v)
print(v.shape)

x = v.reshape(1,4)
print(x)
print(x.shape)

[1 2 3 4]
(4,)
[[1 2 3 4]]
(1, 4)
